services:
  postgres:
    image: postgres:16-alpine
    container_name: amazon_postgres
    environment:
      POSTGRES_DB: amazon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - amazon_network

  redis:
    image: redis:7-alpine
    container_name: amazon_redis
    ports:
      - "6379:6379"
    networks:
      - amazon_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: amazon_backend
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: amazon_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      CACHE_STORE: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_DRIVER: redis
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - amazon_network

networks:
  amazon_network:
    driver: bridge

volumes:
  postgres_data:
